# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Acceso de Profesor',
                'verbose_name_plural': 'Accesos de Profesores',
                'db_table': 'acceso_profesor',
                'ordering': ['-fecha_hora_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_clase', models.TimeField()),
                ('tema_clase', models.TextField(blank=True, help_text='Tema o contenido tratado en esta clase', null=True, verbose_name='Tema de la clase')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('archivo_justificacion', models.FileField(blank=True, null=True, upload_to='justificaciones/')),
                ('fecha_justificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['-fecha', '-hora_clase'],
            },
        ),
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cuenta_como_asistencia', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Asistencia',
                'verbose_name_plural': 'Estados de Asistencia',
                'db_table': 'estado_asistencia',
            },
        ),
        migrations.CreateModel(
            name='SolicitudProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMBIO_HORARIO', 'Cambio de Horario'), ('RESERVA_AULA', 'Reserva de Aula'), ('PERMISO', 'Permiso'), ('MATERIAL', 'Material Didáctico'), ('OTRO', 'Otro')], max_length=30)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PROCESO', 'En Proceso')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
            ],
            options={
                'verbose_name': 'Solicitud de Profesor',
                'verbose_name_plural': 'Solicitudes de Profesores',
                'db_table': 'solicitud_profesor',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AULA', 'Aula'), ('LABORATORIO', 'Laboratorio'), ('AUDITORIO', 'Auditorio'), ('BIBLIOTECA', 'Biblioteca'), ('VIRTUAL', 'Virtual')], max_length=20)),
                ('pabellon', models.CharField(blank=True, max_length=50, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(default=30)),
                ('tiene_proyector', models.BooleanField(default=False)),
                ('tiene_computadoras', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
    ]
