# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('asistencia', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='asistencia.estadoasistencia'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='asistencia.ubicacion'),
        ),
        migrations.AddField(
            model_name='accesoprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_ubicacion', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='accesoprofesor',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_profesor', to='asistencia.ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('curso', 'estudiante', 'fecha', 'hora_clase')},
        ),
    ]
