# Generated by Django 4.2.7 on 2025-11-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tema_clase',
            field=models.TextField(blank=True, help_text='Tema o contenido tratado en esta clase', null=True, verbose_name='Tema de la clase'),
        ),
    ]
