-- INSERTs para tabla estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo)
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'UNIVERSIDAD NACIONAL DE SAN AGUSTIN DE AREQUIPA', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ESCUELA PROFESIONAL : CIENCIA DE LA COMPUTACIÃN', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ALUMNOS MATRICULADOS POR ASIGNATURA', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ASIGNATURA : TRABAJO INTERDISCIPLINAR III', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'CICLO : B - GRUPO : A', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'FECHA : 2025-10-09', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('CUI', 'Nro', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20190652', '1', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20193254', '2', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20204682', '3', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20190755', '4', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20180102', '5', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20173456', '6', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200556', '7', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200730', '8', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20202230', '9', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210691', '10', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210671', '11', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20180683', '12', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20212159', '13', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20212162', '14', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20213122', '15', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20213140', '16', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210689', '17', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210695', '18', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200734', '19', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20213143', '20', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210686', '21', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20190750', '22', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20181740', '23', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20193061', '24', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200724', '25', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200729', '26', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210683', '27', '1705267', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
