-- INSERTs para tabla estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo)
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'UNIVERSIDAD NACIONAL DE SAN AGUSTIN DE AREQUIPA', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ESCUELA PROFESIONAL : CIENCIA DE LA COMPUTACIÃN', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ALUMNOS MATRICULADOS POR ASIGNATURA', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'ASIGNATURA : TRABAJO INTERDISCIPLINAR II', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'CICLO : B - GRUPO : A', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('', 'FECHA : 2025-10-09', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('CUI', 'Nro', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233590', '1', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232284', '2', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230573', '3', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20213145', '4', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20231537', '5', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233598', '6', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20222178', '7', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20222145', '8', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20222179', '9', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233582', '10', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20221737', '11', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230579', '12', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233589', '13', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232279', '14', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20200364', '15', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232276', '16', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232282', '17', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233577', '18', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230585', '19', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20220724', '20', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232274', '21', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233595', '22', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20224274', '23', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230578', '24', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233583', '25', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20204428', '26', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232278', '27', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20213147', '28', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230580', '29', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20231535', '30', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233581', '31', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20222143', '32', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210680', '33', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230584', '34', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20024030', '35', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20231540', '36', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20231533', '37', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20162924', '38', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230571', '39', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233594', '40', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232285', '41', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20223086', '42', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230570', '43', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233593', '44', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20212163', '45', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233597', '46', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20190224', '47', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20224270', '48', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20232277', '49', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20233585', '50', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20210194', '51', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20230582', '52', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
INSERT INTO estudiantes (codigo_estudiante, nombre, curso_codigo, curso_nombre, grupo) VALUES ('20222142', '53', '1703240', 'ALUMNOS MATRICULADOS POR ASIGNATURA | nan | nan | nan | nan', 'B');
