# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(max_length=20)),
                ('grupo', models.CharField(default='A', max_length=10)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('motivo_retiro', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('RETIRADO', 'Retirado'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('EN_PROCESO', 'En Proceso')], default='MATRICULADO', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('es_segunda_matricula', models.BooleanField(default=False)),
                ('es_tercera_matricula', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='curso.curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'ordering': ['-fecha_matricula'],
            },
        ),
    ]
