# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuario.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'curso', 'periodo_academico')},
        ),
    ]
