# Generated by Django 4.2.9 on 2025-10-21 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_red', models.GenericIPAddressField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radio_metros', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
        migrations.AddField(
            model_name='accesoprof',
            name='alerta_generada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesoprof',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_profesor', to='app.curso'),
        ),
        migrations.AddField(
            model_name='accesoprof',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='SolicitudProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JUSTIFICACION', 'Justificación de Inasistencia'), ('CLASE_REMOTA', 'Permiso Clase Virtual/Remota')], max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_clase', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respuesta_secretaria', models.TextField(blank=True, default='')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_profesor', to='app.curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.profesor')),
            ],
            options={
                'verbose_name': 'Solicitud Profesor',
                'verbose_name_plural': 'Solicitudes Profesores',
                'db_table': 'solicitud_profesor',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
