# Generated by Django 4.2.9 on 2025-10-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='silabo',
            table='silabo',
        ),
    ]
