# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(default=3)),
                ('horas_teoria', models.IntegerField(default=2)),
                ('horas_practica', models.IntegerField(default=2)),
                ('horas_laboratorio', models.IntegerField(default=0)),
                ('semestre_recomendado', models.IntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Silabo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('sumilla', models.TextField()),
                ('competencias', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('sistema_evaluacion', models.TextField(blank=True, null=True)),
                ('bibliografia', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='silabos/')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sílabo',
                'verbose_name_plural': 'Sílabos',
                'db_table': 'silabo',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNIDAD', 'Unidad'), ('TEMA', 'Tema'), ('SUBTEMA', 'Subtema')], max_length=20)),
                ('numero', models.IntegerField()),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_semanas', models.IntegerField(default=1)),
                ('orden', models.IntegerField(default=0)),
                ('contenido_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontenidos', to='curso.contenido')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'db_table': 'contenido',
                'ordering': ['silabo', 'orden', 'numero'],
            },
        ),
    ]
