# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='usuario.escuela'),
        ),
        migrations.AddField(
            model_name='curso',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='cursos_siguientes', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='silabo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silabos', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='silabo',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silabos', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='silabo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='curso.silabo'),
        ),
        migrations.AlterUniqueTogether(
            name='silabo',
            unique_together={('curso', 'periodo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='contenido',
            unique_together={('silabo', 'tipo', 'numero')},
        ),
    ]
