# Generated by Django 4.2.7 on 2025-11-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='silabo',
            name='fecha_subida',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el profesor subió el sílabo', null=True, verbose_name='Fecha de subida'),
        ),
        migrations.AddField(
            model_name='silabo',
            name='subido',
            field=models.BooleanField(default=False, help_text='Indica si el sílabo ha sido subido por el profesor', verbose_name='Sílabo subido'),
        ),
    ]
