# Generated by Django 4.2.7 on 2025-11-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_silabo_fecha_subida_silabo_subido'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tiene_grupo_b',
            field=models.BooleanField(default=False, help_text='Si el curso tiene dos grupos (A y B)'),
        ),
    ]
