# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dni', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='DNI debe tener 8 dígitos', regex='^\\d{8}$')])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('direccion_ip_ultimo_acceso', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración IP',
                'verbose_name_plural': 'Configuraciones IP',
                'db_table': 'configuracion_ip',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('facultad', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'escuela',
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
                'db_table': 'estado_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='TipoProfesor',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Profesor',
                'verbose_name_plural': 'Tipos de Profesor',
                'db_table': 'tipo_profesor',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrador', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_acceso', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_cuenta',
            field=models.ForeignKey(default='ACTIVO', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuario.estadocuenta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos_usuario',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuario.permiso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuario.tipousuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='secretaria', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area_asignada', models.CharField(max_length=100)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretarias', to='usuario.escuela')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'db_table': 'secretaria',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.CharField(blank=True, max_length=200, null=True)),
                ('grado_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('cv_url', models.URLField(blank=True, null=True)),
                ('escuela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='usuario.escuela')),
                ('tipo_profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesores', to='usuario.tipoprofesor')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estudiante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_estudiante', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('semestre_actual', models.IntegerField(default=1)),
                ('creditos_aprobados', models.IntegerField(default=0)),
                ('promedio_ponderado', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='usuario.escuela')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='AlertaAccesoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ip', to='usuario.profesor')),
            ],
            options={
                'verbose_name': 'Alerta de Acceso IP',
                'verbose_name_plural': 'Alertas de Acceso IP',
                'db_table': 'alerta_acceso_ip',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
