# Generated by Django 4.2.7 on 2025-11-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración IP',
                'verbose_name_plural': 'Configuraciones IP',
                'db_table': 'configuracion_ip',
            },
        ),
        migrations.CreateModel(
            name='AlertaAccesoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=200)),
                ('leida', models.BooleanField(default=False)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ip', to='usuario.profesor')),
            ],
            options={
                'verbose_name': 'Alerta de Acceso IP',
                'verbose_name_plural': 'Alertas de Acceso IP',
                'db_table': 'alerta_acceso_ip',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
