# Generated by Django 4.2.7 on 2025-11-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_configuracionip_alertaaccesoip'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
