# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(default='2025-A', max_length=20)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('RETIRADO', 'Retirado')], default='MATRICULADO', max_length=20)),
            ],
            options={
                'db_table': 'matricula_horario',
            },
        ),
    ]
