# Generated by Django 5.1.13 on 2025-11-17 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario', '0002_initial'),
        ('usuario', '0003_escuela_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(default='2025-A', max_length=20)),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('RETIRADO', 'Retirado')], default='MATRICULADO', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_horario', to='usuario.estudiante')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_horario', to='horario.horario')),
            ],
            options={
                'db_table': 'matricula_horario',
                'unique_together': {('estudiante', 'horario', 'periodo_academico')},
            },
        ),
    ]
