# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula_horario', '0001_initial'),
        ('usuario', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculahorario',
            name='estudiante',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='matriculas_horario',
                to='usuario.estudiante',
                null=True,      # ← FIX 1
                blank=True      # ← FIX 2
            ),
        ),
        migrations.AddField(
            model_name='matriculahorario',
            name='horario',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='matriculas_horario',
                to='horario.horario',
                null=True,
                blank=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name='matriculahorario',
            unique_together={('estudiante', 'horario', 'periodo_academico')},
        ),
    ]
