# Generated by Django 4.2.7 on 2025-11-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('matricula_horario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculahorario',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_horario', to='usuario.estudiante'),
        ),
    ]
