# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, help_text='Peso en porcentaje para el cálculo de la nota final', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Tipo de Nota',
                'verbose_name_plural': 'Tipos de Nota',
                'db_table': 'tipo_nota',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_evaluacion', models.IntegerField(default=1)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mediana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desviacion_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cantidad_aprobados', models.IntegerField(default=0)),
                ('cantidad_desaprobados', models.IntegerField(default=0)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_evaluacion', to='curso.curso')),
            ],
            options={
                'verbose_name': 'Estadística de Evaluación',
                'verbose_name_plural': 'Estadísticas de Evaluaciones',
                'db_table': 'estadistica_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Nota de 0 a 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('numero_evaluacion', models.IntegerField(default=1, help_text='Número de evaluación del mismo tipo (ej: Práctica 1, Práctica 2)')),
                ('fecha_evaluacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='curso.curso')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
