# Generated by Django 4.2.7 on 2025-11-26 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], default=1, help_text='Unidad académica a la que aplica esta configuración')),
                ('fecha_limite_subida_notas', models.DateTimeField(help_text='Fecha y hora máxima establecida por Secretaría para la subida de notas.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Unidad',
                'verbose_name_plural': 'Configuraciones de Unidad',
                'db_table': 'configuracion_unidad',
                'ordering': ['curso__nombre', 'unidad'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_evaluacion', models.IntegerField(default=1)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mediana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desviacion_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cantidad_aprobados', models.IntegerField(default=0)),
                ('cantidad_desaprobados', models.IntegerField(default=0)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadística de Evaluación',
                'verbose_name_plural': 'Estadísticas de Evaluaciones',
                'db_table': 'estadistica_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='FechaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('PRIMER_PARCIAL', 'Primer Parcial'), ('SEGUNDO_PARCIAL', 'Segundo Parcial'), ('TERCER_PARCIAL', 'Tercer Parcial')], help_text='Tipo de examen parcial', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la semana de examen (ej: 3/11/2025)')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la semana de examen (ej: 7/11/2025)')),
                ('periodo_academico', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Indicaciones, material permitido, temas a evaluar, etc.', null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fecha de Examen',
                'verbose_name_plural': 'Fechas de Exámenes',
                'db_table': 'fecha_examen',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PARCIAL', 'Examen Parcial'), ('CONTINUA', 'Evaluación Continua')], default='PARCIAL', help_text='Parcial (exámenes) o Continua (prácticas)', max_length=20)),
                ('unidad', models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], default=1, help_text='Unidad académica (1, 2 o 3)')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Nota de 0 a 20', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('numero_evaluacion', models.IntegerField(default=1, help_text='Número de evaluación del mismo tipo (ej: Práctica 1, Práctica 2)')),
                ('fecha_evaluacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_examen', models.FileField(blank=True, help_text='Archivo escaneado del examen (solo para parciales)', null=True, upload_to='examenes/')),
                ('fecha_limite_edicion', models.DateTimeField(blank=True, help_text='Fecha límite para editar la nota (1 semana después del registro)', null=True)),
                ('puede_editar', models.BooleanField(default=True, help_text='Indica si la nota aún puede ser editada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('notificado', models.BooleanField(default=False, help_text='Indica si ya se envió la notificación')),
                ('dias_anticipacion', models.IntegerField(choices=[(1, '1 día antes'), (2, '2 días antes'), (3, '3 días antes'), (7, '1 semana antes')], default=1, help_text='Días de anticipación para la notificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Fecha en que se envió la notificación', null=True)),
            ],
            options={
                'verbose_name': 'Recordatorio de Examen',
                'verbose_name_plural': 'Recordatorios de Exámenes',
                'db_table': 'recordatorio_examen',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_porcentual', models.DecimalField(decimal_places=2, help_text='Peso en porcentaje para el cálculo de la nota final', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Tipo de Nota',
                'verbose_name_plural': 'Tipos de Nota',
                'db_table': 'tipo_nota',
            },
        ),
        migrations.CreateModel(
            name='ReporteNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], help_text='Unidad académica del reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del profesor', null=True)),
                ('promedio_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_maxima_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_minima_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aprobados_parcial', models.IntegerField(default=0)),
                ('desaprobados_parcial', models.IntegerField(default=0)),
                ('promedio_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_maxima_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_minima_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aprobados_continua', models.IntegerField(default=0)),
                ('desaprobados_continua', models.IntegerField(default=0)),
                ('examen_nota_mayor', models.FileField(blank=True, help_text='Examen del estudiante con mayor nota', null=True, upload_to='reportes/examenes/')),
                ('examen_nota_menor', models.FileField(blank=True, help_text='Examen del estudiante con menor nota', null=True, upload_to='reportes/examenes/')),
                ('examen_nota_promedio', models.FileField(blank=True, help_text='Examen del estudiante con nota promedio', null=True, upload_to='reportes/examenes/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_notas', to='curso.curso')),
            ],
            options={
                'verbose_name': 'Reporte de Notas',
                'verbose_name_plural': 'Reportes de Notas',
                'db_table': 'reporte_notas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
