# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportenotas',
            name='estudiante_nota_mayor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_mayor', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='reportenotas',
            name='estudiante_nota_menor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_menor', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='reportenotas',
            name='estudiante_nota_promedio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_promedio', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='reportenotas',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='reportenotas',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordatorioexamen',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_examenes', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='recordatorioexamen',
            name='fecha_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='evaluacion.fechaexamen'),
        ),
        migrations.AddField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_registradas', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='evaluacion.tiponota'),
        ),
        migrations.AddField(
            model_name='fechaexamen',
            name='contenido_evaluado',
            field=models.ManyToManyField(blank=True, help_text='Contenidos que serán evaluados en este examen', related_name='examenes', to='curso.contenido'),
        ),
        migrations.AddField(
            model_name='fechaexamen',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_examenes', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='fechaexamen',
            name='profesor_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_programados', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='estadisticaevaluacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_evaluacion', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='estadisticaevaluacion',
            name='tipo_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='evaluacion.tiponota'),
        ),
        migrations.AddField(
            model_name='configuracionunidad',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_unidad', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='configuracionunidad',
            name='establecido_por',
            field=models.ForeignKey(help_text='Usuario de Secretaría/Administrador que definió el límite.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recordatorioexamen',
            unique_together={('estudiante', 'fecha_examen')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('curso', 'estudiante', 'categoria', 'unidad', 'numero_evaluacion')},
        ),
        migrations.AlterUniqueTogether(
            name='fechaexamen',
            unique_together={('curso', 'tipo_examen', 'periodo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaevaluacion',
            unique_together={('curso', 'tipo_nota', 'numero_evaluacion', 'periodo_academico')},
        ),
        migrations.AlterUniqueTogether(
            name='configuracionunidad',
            unique_together={('curso', 'unidad')},
        ),
    ]
