# Generated by Django 5.2.7 on 2025-11-02 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluacion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuario.estudiante'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='evaluacion.tiponota'),
        ),
        migrations.AddField(
            model_name='estadisticaevaluacion',
            name='tipo_nota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='evaluacion.tiponota'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('curso', 'estudiante', 'tipo_nota', 'numero_evaluacion')},
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaevaluacion',
            unique_together={('curso', 'tipo_nota', 'numero_evaluacion', 'periodo_academico')},
        ),
    ]
