# Generated by Django 4.2.7 on 2025-11-02 22:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_escuela_is_active'),
        ('curso', '0002_initial'),
        ('evaluacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_examen', models.IntegerField(default=1, help_text='Número del examen parcial (1, 2 o 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la semana de examen')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la semana de examen')),
                ('dia_examen', models.DateField(blank=True, help_text='Día específico del examen dentro de la semana', null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('periodo_academico', models.CharField(max_length=20)),
                ('aula', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contenido_evaluado', models.ManyToManyField(blank=True, help_text='Contenidos que serán evaluados en este examen', related_name='examenes', to='curso.contenido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_examenes', to='curso.curso')),
                ('profesor_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_programados', to='usuario.profesor')),
                ('tipo_examen', models.ForeignKey(limit_choices_to={'codigo__in': ['EXAMEN_PARCIAL', 'EXAMEN_FINAL']}, on_delete=django.db.models.deletion.PROTECT, related_name='fechas_examen', to='evaluacion.tiponota')),
            ],
            options={
                'verbose_name': 'Fecha de Examen',
                'verbose_name_plural': 'Fechas de Exámenes',
                'db_table': 'fecha_examen',
                'ordering': ['fecha_inicio', 'hora_inicio'],
                'unique_together': {('curso', 'tipo_examen', 'numero_examen', 'periodo_academico')},
            },
        ),
        migrations.CreateModel(
            name='RecordatorioExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('notificado', models.BooleanField(default=False, help_text='Indica si ya se envió la notificación')),
                ('dias_anticipacion', models.IntegerField(choices=[(1, '1 día antes'), (2, '2 días antes'), (3, '3 días antes'), (7, '1 semana antes')], default=1, help_text='Días de anticipación para la notificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, help_text='Fecha en que se envió la notificación', null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_examenes', to='usuario.estudiante')),
                ('fecha_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='evaluacion.fechaexamen')),
            ],
            options={
                'verbose_name': 'Recordatorio de Examen',
                'verbose_name_plural': 'Recordatorios de Exámenes',
                'db_table': 'recordatorio_examen',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('estudiante', 'fecha_examen')},
            },
        ),
    ]
