# Generated by Django 4.2.7 on 2026-01-06 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_agregar_campos_silabo'),
        ('usuario', '0001_initial'),
        ('evaluacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesosEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(help_text='Ejemplo: 2024-1, 2024-2', max_length=10)),
                ('peso_parcial_u1', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Parcial Unidad 1 (%)')),
                ('peso_continua_u1', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Continua Unidad 1 (%)')),
                ('peso_parcial_u2', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Parcial Unidad 2 (%)')),
                ('peso_continua_u2', models.DecimalField(decimal_places=2, default=15.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Continua Unidad 2 (%)')),
                ('peso_parcial_u3', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Parcial Unidad 3 (%)')),
                ('peso_continua_u3', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Continua Unidad 3 (%)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos_evaluacion', to='curso.curso')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesos_registrados', to='usuario.profesor')),
            ],
            options={
                'verbose_name': 'Peso de Evaluación',
                'verbose_name_plural': 'Pesos de Evaluación',
                'db_table': 'pesos_evaluacion',
                'unique_together': {('curso', 'periodo_academico')},
            },
        ),
    ]
