# Generated by Django 4.2.7 on 2025-11-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_initial'),
        ('evaluacion', '0003_fechaexamen_recordatorioexamen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fechaexamen',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='dia_examen',
            field=models.DateField(help_text='Día específico del examen dentro de la semana'),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='fecha_fin',
            field=models.DateField(help_text='Fecha de fin de la semana de examen (ej: 7/11/2025)'),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='fecha_inicio',
            field=models.DateField(help_text='Fecha de inicio de la semana de examen (ej: 3/11/2025)'),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='hora_fin',
            field=models.TimeField(help_text='Hora de fin del examen'),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='hora_inicio',
            field=models.TimeField(help_text='Hora de inicio del examen'),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Indicaciones, material permitido, temas a evaluar, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='fechaexamen',
            name='tipo_examen',
            field=models.CharField(choices=[('PRIMER_PARCIAL', 'Primer Parcial'), ('SEGUNDO_PARCIAL', 'Segundo Parcial'), ('TERCER_PARCIAL', 'Tercer Parcial')], help_text='Tipo de examen parcial', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='fechaexamen',
            unique_together={('curso', 'tipo_examen', 'periodo_academico')},
        ),
        migrations.RemoveField(
            model_name='fechaexamen',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='fechaexamen',
            name='numero_examen',
        ),
    ]
