# Generated by Django 4.2.7 on 2025-11-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_alter_fechaexamen_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechaexamen',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Fecha de Examen', 'verbose_name_plural': 'Fechas de Exámenes'},
        ),
        migrations.RemoveField(
            model_name='fechaexamen',
            name='dia_examen',
        ),
        migrations.RemoveField(
            model_name='fechaexamen',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='fechaexamen',
            name='hora_inicio',
        ),
    ]
