# Generated by Django 4.2.7 on 2025-11-02 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_escuela_is_active'),
        ('curso', '0003_silabo_fecha_subida_silabo_subido'),
        ('evaluacion', '0005_alter_fechaexamen_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nota',
            name='archivo_examen',
            field=models.FileField(blank=True, help_text='Archivo escaneado del examen (solo para parciales)', null=True, upload_to='examenes/'),
        ),
        migrations.AddField(
            model_name='nota',
            name='categoria',
            field=models.CharField(choices=[('PARCIAL', 'Examen Parcial'), ('CONTINUA', 'Evaluación Continua')], default='PARCIAL', help_text='Parcial (exámenes) o Continua (prácticas)', max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha_limite_edicion',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para editar la nota (1 semana después del registro)', null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='puede_editar',
            field=models.BooleanField(default=True, help_text='Indica si la nota aún puede ser editada'),
        ),
        migrations.AddField(
            model_name='nota',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_registradas', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='nota',
            name='unidad',
            field=models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], default=1, help_text='Unidad académica (1, 2 o 3)'),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('curso', 'estudiante', 'categoria', 'unidad', 'numero_evaluacion')},
        ),
    ]
