# Generated by Django 4.2.7 on 2025-11-04 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_silabo_fecha_subida_silabo_subido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluacion', '0006_alter_nota_unique_together_nota_archivo_examen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], default=1, help_text='Unidad académica a la que aplica esta configuración')),
                ('fecha_limite_subida_notas', models.DateTimeField(help_text='Fecha y hora máxima establecida por Secretaría para la subida de notas.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_unidad', to='curso.curso')),
                ('establecido_por', models.ForeignKey(help_text='Usuario de Secretaría/Administrador que definió el límite.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Unidad',
                'verbose_name_plural': 'Configuraciones de Unidad',
                'db_table': 'configuracion_unidad',
                'ordering': ['curso__nombre', 'unidad'],
                'unique_together': {('curso', 'unidad')},
            },
        ),
    ]
