# Generated by Django 4.2.7 on 2025-11-05 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0003_silabo_fecha_subida_silabo_subido'),
        ('usuario', '0003_escuela_is_active'),
        ('evaluacion', '0007_configuracionunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.IntegerField(choices=[(1, 'Unidad 1'), (2, 'Unidad 2'), (3, 'Unidad 3')], help_text='Unidad académica del reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del profesor', null=True)),
                ('promedio_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_maxima_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_minima_parcial', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aprobados_parcial', models.IntegerField(default=0)),
                ('desaprobados_parcial', models.IntegerField(default=0)),
                ('promedio_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_maxima_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nota_minima_continua', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('aprobados_continua', models.IntegerField(default=0)),
                ('desaprobados_continua', models.IntegerField(default=0)),
                ('examen_nota_mayor', models.FileField(blank=True, help_text='Examen del estudiante con mayor nota', null=True, upload_to='reportes/examenes/')),
                ('examen_nota_menor', models.FileField(blank=True, help_text='Examen del estudiante con menor nota', null=True, upload_to='reportes/examenes/')),
                ('examen_nota_promedio', models.FileField(blank=True, help_text='Examen del estudiante con nota promedio', null=True, upload_to='reportes/examenes/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_notas', to='curso.curso')),
                ('estudiante_nota_mayor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_mayor', to='usuario.estudiante')),
                ('estudiante_nota_menor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_menor', to='usuario.estudiante')),
                ('estudiante_nota_promedio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_nota_promedio', to='usuario.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to='usuario.profesor')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Notas',
                'verbose_name_plural': 'Reportes de Notas',
                'db_table': 'reporte_notas',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
