# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_clase', models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICA', 'Práctica'), ('LABORATORIO', 'Laboratorio'), ('RESERVA', 'Reserva de Ambiente')], max_length=20)),
                ('periodo_academico', models.CharField(max_length=20)),
                ('grupo', models.CharField(default='A', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_reserva_extra', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo_academico', models.CharField(default='2025-B', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='CONFIRMADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva de Ambiente',
                'verbose_name_plural': 'Reservas de Ambiente',
                'db_table': 'reserva_ambiente',
                'ordering': ['fecha_reserva', 'hora_inicio'],
            },
        ),
    ]
