# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0002_initial'),
        ('horario', '0001_initial'),
        ('usuario', '0001_initial'),
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaambiente',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_ambiente', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='reservaambiente',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='asistencia.ubicacion'),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='usuario.profesor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='asistencia.ubicacion'),
        ),
        migrations.AlterUniqueTogether(
            name='reservaambiente',
            unique_together={('ubicacion', 'fecha_reserva', 'hora_inicio')},
        ),
    ]
