# Generated by Django 4.2.7 on 2025-11-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='es_reserva_extra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='tipo_clase',
            field=models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICA', 'Práctica'), ('LABORATORIO', 'Laboratorio'), ('RESERVA', 'Reserva de Ambiente')], max_length=20),
        ),
    ]
