# Generated by Django 4.2.7 on 2025-12-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_initial'),
        ('horario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaambiente',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_ambiente', to='curso.curso'),
        ),
    ]
