# Generated by Django 4.2.7 on 2025-11-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_silabo_fecha_subida_silabo_subido'),
        ('horario', '0003_horario_es_reserva_extra_alter_horario_tipo_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='curso.curso'),
        ),
    ]
