# Generated by Django 4.2.7 on 2026-01-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_agregar_campos_silabo'),
        ('horario', '0003_reservaambiente_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaambiente',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_ambiente', to='curso.curso'),
        ),
    ]
