# Generated by Django 4.2.7 on 2025-11-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_asistencia_tema_clase'),
        ('usuario', '0003_escuela_is_active'),
        ('horario', '0004_alter_horario_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo_academico', models.CharField(default='2025-B', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='CONFIRMADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_ambiente', to='usuario.profesor')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='asistencia.ubicacion')),
            ],
            options={
                'verbose_name': 'Reserva de Ambiente',
                'verbose_name_plural': 'Reservas de Ambiente',
                'db_table': 'reserva_ambiente',
                'ordering': ['fecha_reserva', 'hora_inicio'],
                'unique_together': {('ubicacion', 'fecha_reserva', 'hora_inicio')},
            },
        ),
    ]
