# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D'), ('E', 'Grupo E')], help_text='Grupo del laboratorio (A, B, C, D, E)', max_length=1)),
                ('capacidad_maxima', models.IntegerField(default=20, help_text='Capacidad máxima de estudiantes (por defecto 20)')),
                ('periodo_academico', models.CharField(default='2025-B', max_length=10)),
                ('publicado', models.BooleanField(default=False, help_text='Si está publicado, los estudiantes pueden matricularse')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('es_grupo_adicional', models.BooleanField(default=False, help_text='Si es True, cualquier estudiante puede matricularse (grupos C, D, E)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorios_grupos', to='curso.curso')),
                ('horario', models.ForeignKey(help_text='Horario asignado a este grupo de laboratorio', on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_grupo', to='horario.horario')),
            ],
            options={
                'verbose_name': 'Grupo de Laboratorio',
                'verbose_name_plural': 'Grupos de Laboratorio',
                'db_table': 'laboratorio_grupo',
                'ordering': ['curso', 'grupo'],
                'unique_together': {('curso', 'grupo', 'periodo_academico')},
            },
        ),
    ]
