# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(default='2025-A', max_length=10)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('RETIRADO', 'Retirado'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], default='MATRICULADO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso', to='curso.curso')),
            ],
            options={
                'verbose_name': 'Matrícula de Curso',
                'verbose_name_plural': 'Matrículas de Curso',
                'db_table': 'matricula_curso',
            },
        ),
    ]
