# Generated by Django 4.2.7 on 2025-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('matricula_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculacurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_curso', to='usuario.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='matriculacurso',
            unique_together={('estudiante', 'curso', 'periodo_academico')},
        ),
    ]
